pluralizelisttitles = "false"
paginate = 6

[menu]
[[menu.main]]
    identifier = 'arrangementarchive'
    name = 'Arrangementer'
    url = '/arrangementarkiv/'

disableKinds = ["taxonomy","taxonomyTerm"]

baseURL = '/'
languageCode = 'nb-NO'
title = 'Digdir DevOps | Leikanger 2022'

DefaultContentLanguage = "nb"

[params]
    icon = '/images/logo.png'




