disableKinds = ["taxonomy","taxonomyTerm"]
pluralizelisttitles = "false"
paginate = 6

[menu]
[[menu.main]]
    identifier = 'arrangementarchive'
    name = 'Arrangementer'
    url = '/arrangementarkiv/'

baseURL = '/'
languageCode = 'nb-NO'
title = 'Digdir DevOps'

DefaultContentLanguage = "nb"

[params]
    icon = '/images/digdir_devops.svg'




