disableKinds = ["taxonomy","taxonomyTerm"]

baseURL = 'https://bookish-umbrella-3e531b6d.pages.github.io/'
languageCode = 'nb-NO'
title = 'Digdir DevOps | Leikanger 2022'

DefaultContentLanguage = "nb"

pluralizelisttitles = "false"

paginate = 2

[params]
    icon = '/images/logo.png'




