disableKinds = ["taxonomy","taxonomyTerm"]

baseURL = '/'
languageCode = 'nb-NO'
title = 'Digdir DevOps | Leikanger 2022'

DefaultContentLanguage = "nb"

pluralizelisttitles = "false"

paginate = 2

[params]
    icon = '/images/logo.png'




